import streamlit as st


def render() -> None:
    st.sidebar.info(
        "Based on this project, we propose three Apple features that turn personal GPS data "
        "into actionable sustainability insights - each one grounded in the technical work above."
    )

    # ── Feature 1 ─────────────────────────────────────────────────────────────
    st.markdown("#### 1. Commute Copilot")
    st.info(
        "Your iPhone quietly tracks how you get around, estimates your carbon footprint, "
        "and tells you exactly which trips are worth changing - with specific numbers, not vague advice."
    )

    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown("**How it works**")
        st.markdown(
            "- GPS and motion sensors classify each trip: walk, bike, transit, or car\n"
            "- CO₂ is calculated on-device - nothing leaves your phone\n"
            '- A weekly summary is generated by Claude: *"You drove 2.1 km to the gym 4× '
            'this week - biking saves ~1.4 kg CO₂/week and adds ~6 min per trip"*\n'
            "- Every number is fact-checked by the Judge+Critic pipeline before you see it"
        )
    with col_b:
        st.markdown("**Why Apple can build this**")
        st.markdown(
            "- Apple Maps already has cycling routes and transit directions\n"
            "- Apple Health already tracks movement and activity\n"
            "- On-device ML (Core ML) keeps all location data private\n"
            "- Fits Apple's existing environmental commitments"
        )

    st.divider()

    # ── Feature 2 ─────────────────────────────────────────────────────────────
    st.markdown("#### 2. Carbon Ring")
    st.info(
        "A new ring in Apple Health that rewards low-carbon travel - "
        "points go toward real environmental impact, not product purchases."
    )

    col_c, col_d = st.columns(2)
    with col_c:
        st.markdown("**How it works**")
        st.markdown(
            "- Each trip earns points based on how much CO₂ it saved vs. driving\n"
            "- Points build a weekly Carbon Ring in Apple Health\n"
            "- Rewards: leaderboards with friends, carbon offset donations, or Watch features\n"
            "- Optional: see what your contacts chose (opt-in social nudge)"
        )
    with col_d:
        st.markdown("**Why it works**")
        st.markdown(
            "- Our simulation of 15 commuters over 7 days showed car usage and CO₂ dropped "
            "at every nudge level, with leaderboards producing the biggest shift\n"
            "- Visible rewards are one of the most well-supported tools for changing travel habits\n"
            "- Points fund impact, not purchases - this is nudging, not greenwashing"
        )
    st.divider()

    # ── Feature 3 ─────────────────────────────────────────────────────────────
    st.markdown("#### 3. Apple Green Impact")
    st.info(
        "Individual footprints, aggregated privately, give Apple a real user-behaviour metric "
        "to include in its annual sustainability reports."
    )

    col_e, col_f = st.columns(2)
    with col_e:
        st.markdown("**How it works**")
        st.markdown(
            "- On-device footprints are aggregated with differential privacy - "
            "Apple sees population trends, never individual trips\n"
            '- Apple can report: *"Our users collectively avoided X million kg CO₂ '
            'this year through Commute Copilot"*\n'
            "- Tracks adoption rate, mode shifts, and estimated savings by city over time"
        )
    with col_f:
        st.markdown("**Why it matters for Apple**")
        st.markdown(
            "- Apple already publishes Environmental Progress Reports - "
            "this adds a user-behaviour metric alongside supply-chain metrics\n"
            "- The story becomes: Apple doesn't just make green products, "
            "it helps users live more sustainably\n"
            "- On-device privacy is a competitive advantage no Android competitor can easily match"
        )

    st.markdown("**ESG Score → Stock Value**")
    st.markdown(
        "A better ESG score makes Apple more attractive to the \\$30T+ market of ESG-focused funds. "
        "Most tech ESG scores are based on supply-chain metrics - Apple Green Impact adds something "
        "rare: a user-behaviour metric at scale. Better ESG score → inclusion in more ESG portfolios "
        "→ broader investor base → higher stock valuation."
    )
